export enum DataTypes {
  Int = "INT",
  Smallint = "SMALLINT",
  Bigint = "BIGINT",
  Decimal = "DECIMAL",
  Numeric = "NUMERIC",
  Float = "FLOAT",
  Double = "DOUBLE",
  Real = "REAL",
  Char = "CHAR",
  Varchar = "VARCHAR",
  Text = "TEXT",
  Date = "DATE",
  Time = "TIME",
  Timestamp = "TIMESTAMP",
  Datetime = "DATETIME",
  Boolean = "BOOLEAN",
  Binary = "BINARY",
  Varbinary = "VARBINARY",
  Blob = "BLOB",
  Json = "JSON",
  Uuid = "UUID",
  Enum = "ENUM",
  Set = "SET",
}
